### Site Settings ###
title               : Ana Beatriz ();
description         : >-                               # >- means to ignore newlines until "url:"
                      Hi, I'm Ana Beatriz Neri, developer back end Java and Groovy Grails.
                      I found myself in the Dev area the possibility of changing people around me and me.
                        I love to help the community of T. I, and of cute cats! 
                        Take a run at my blog and follow me on social networks to be friends!

url                 : "anabneri.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/anabneri.github.io"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Ana Beatriz
  image             : /photos/euzinha.jpg
  behance           : your_username
# dribbble          : your_username
  email             : username@domain.com
  facebook          : 
  github            : 
# gitlab            : your_username
  instagram         : 
  linkedin          : 
  medium            : 
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : 
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock