### Site Settings ###
title               : Ana Beatriz ();
description         : >-                               # >- means to ignore newlines until "url:"
                      Sou a Ana Beatriz, tenho 19 anos e Desenvolvedora Java e Groovy.
                      Adepta a movimento de mulheres na tecnologia. Amante de livros, séries e gatinhos :)
                      Welcome to my site/blog :v

url                 : "anabneri.github.io"                               # base hostname & protocol for your site (e.g. http://example.com)
baseurl             : "/anabneri.github.io"                    # subpath of your site (e.g. /blog) [IMPORTANT: use "" if your are hosting at https://username.github.io directly]
repository          : YoussefRaafatNasry/portfolYOU    # repository metadata on GitHub Pages [know more at https://help.github.com/en/articles/repository-metadata-on-github-pages]
#remote_theme       : YoussefRaafatNasry/portfolYOU    # uncomment this if you are using it as a remote theme

### Author Info ###
author:
  name              : Ana Beatriz
  image             : /photos/euzinha.jpg
  behance           : your_username
# dribbble          : your_username
  email             : username@domain.com
  facebook          : 
  github            : 
# gitlab            : your_username
  instagram         : 
  linkedin          : 
  medium            : 
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : 
# vimeo             : your_username
# youtube           : your_channel_name


### Pagination ###
paginate: 6
paginate_path: "/articles/page-:num/"


### Posts Permalink ###
permalink: articles/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


### Exclude from processing ###
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock